{{- range .Values.accounts -}}
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}
  namespace: default
  labels:
{{ include "kergiva.labels" $ | indent 4 }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .name }}
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .name }}
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .name }}
subjects:
- namespace: default
  kind: ServiceAccount
  name: {{ .name }}

{{- end -}}