{{- if .Values.serviceAccount.create -}}
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kergiva.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "kergiva.labels" . | indent 4 }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "kergiva.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "kergiva.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "kergiva.serviceAccountName" . }}
subjects:
- namespace: {{ .Release.Namespace }}
  kind: ServiceAccount
  name: {{ template "kergiva.serviceAccountName" . }}

{{- end -}}