apiVersion: kubedb.com/v1alpha2
kind: MySQL
metadata:
  name: {{ .Values.database_name }}
spec:
  version: {{ .Values.database_version }}
  storageType: Durable
  storage:
    storageClassName: {{ .Values.storage_class }}
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: {{ .Values.resources_request.storage }}
  requireSSL: true
  tls:
    issuerRef:
      apiGroup: cert-manager.io
      kind: ClusterIssuer
      name: letsencrypt-prod
    certificates:
    - alias: server
      subject:
        organizations:
        - kubedb:server
      dnsNames:
      - "npidb.arroyo.turnbros.app"
  podTemplate:
    spec:
      resources:
        requests:
          cpu: {{ .Values.resources_request.cpu }}
          memory: {{ .Values.resources_request.memory }}
        limits:
          cpu: {{ .Values.resources_limit.cpu }}
          memory: {{ .Values.resources_limit.memory }}
  terminationPolicy: DoNotTerminate

