apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: mysql-db
    app.kubernetes.io/managed-by: kubedb.com
    app.kubernetes.io/name: mysqls.kubedb.com
  name: mysql-db-nodeport
spec:
  ports:
  - name: primary
    port: 3306
    protocol: TCP
    targetPort: db
  selector:
    app.kubernetes.io/instance: mysql-db
    app.kubernetes.io/managed-by: kubedb.com
    app.kubernetes.io/name: mysqls.kubedb.com
  sessionAffinity: None
  type: NodePort