
### ACCOUNTS ###
accounts:
  - name: kergiva-org-admin
    type: admin

### DEPLOYMENTS ###
deployments:
  - name: kergiva-org-web
    replicas: 1
    image:
      repo: docker.pkg.github.com/rationalhealthcare/kgweb/kgweb
      tag: latest
      pull_poicy: Always
      pull_secret: regcred
    security:
      read_only_root_filesystem: true
      run_as_non_root: true
      run_as_user: 1000
      run_as_group: 1000
      drop_all_capabilities: true
      pod_fs_group: 1000
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    probes:
      liveness:
        path: /
        port: 80
      readiness:
        path: /
        port: 80
    init_containers:
      - name: install
        image: busybox
        command: ['sh', '-c', 'mkdir -p /var/cache/nginx && chown 1000:1000 /var/cache/nginx']
        volumeMounts:
          - mountPath: /var/cache
            name: cache-volume
    environment_variables:
      NGINX_PORT: 80
    volume_mounts:
      site-config: /etc/nginx/conf.d/
      cache-volume: /var/cache
      run-volume: /var/run
    endpoints:
      - create_ingress: true
        hosts: 
          - kergiva.org
          - www.kergiva.org
        path: /
        container_port: 80
        protocol: TCP

  - name: kergiva-org-app
    replicas: 1
    image:
      repo: docker.pkg.github.com/rationalhealthcare/vuetest2/kergiva-web
      tag: latest
      pull_poicy: Always
      pull_secret: regcred
    security:
      read_only_root_filesystem: true
      run_as_non_root: true
      run_as_user: 1000
      run_as_group: 1000
      drop_all_capabilities: true
      pod_fs_group: 1000
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    probes:
      liveness:
        path: /
        port: 80
      readiness:
        path: /
        port: 80
    init_containers:
      - name: install
        image: busybox
        command: ['sh', '-c', 'mkdir -p /var/cache/nginx && chown 1000:1000 /var/cache/nginx']
        volumeMounts:
          - mountPath: /var/cache
            name: cache-volume
    environment_variables:
      NGINX_PORT: 80
    volume_mounts:
      site-config: /etc/nginx/conf.d/
      cache-volume: /var/cache
      run-volume: /var/run
    endpoints:
      - create_ingress: true
        hosts: 
          - kergiva.app
        path: /
        container_port: 80
        protocol: TCP
  
          
### VOLUME STUFF ###
volumes:
  - name: nginx-config
    configMap:
      name: site-configmap
  - name: site-config
    configMap:
      name: site-configmap
  - name: cache-volume
    emptyDir: {}
  - name: run-volume
    emptyDir: {}


### Ingress Annotations Stuff ###
ingress_annotations:
  kubernetes.io/ingress.class: nginx
  cert-manager.io/cluster-issuer: letsencrypt-prod

### Node Selector Stuff ###
nodeSelector: {}

### Tolerations Stuff ###
tolerations: []

### Affinity Stuff ###
affinity: {}